---
# General Configuration
indexer_domain: "example.com"
admin_email: "admin@example.com"

# Base Packages to Install
base_packages:
  - curl
  - wget
  - unzip
  - net-tools
  - python3
  - python3-pip
  - git
  - vim
  - htop
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release

# Nginx Configuration
nginx_port: 443
nginx_upstream_servers: []
# Example:
# nginx_upstream_servers:
#   - "192.168.1.10:8080"
#   - "192.168.1.11:8080"

# ClickHouse Configuration
clickhouse_http_port: 8123
clickhouse_tcp_port: 9000
clickhouse_interserver_port: 9009
clickhouse_data_dir: "/var/lib/clickhouse"
clickhouse_log_dir: "/var/log/clickhouse-server"

# Prometheus Configuration
prometheus_port: 9090
prometheus_data_dir: "/var/lib/prometheus"
prometheus_retention: "15d"
prometheus_scrape_interval: "15s"

# Grafana Configuration
grafana_port: 3000
grafana_admin_user: "admin"
grafana_admin_password: "changeme"
grafana_data_dir: "/var/lib/grafana"

# SSL Certificate Configuration
certbot_create_if_missing: true
certbot_create_method: standalone
certbot_admin_email: "{{ admin_email }}"
certbot_certs:
  - domains:
      - "{{ indexer_domain }}"
      - "www.{{ indexer_domain }}"
certbot_create_extra_args: ""
certbot_auto_renew: true
certbot_auto_renew_user: "root"
certbot_auto_renew_hour: "3"
certbot_auto_renew_minute: "30"

# Custom Binaries Configuration
custom_binaries:
  - name: "indexer"
    url: "https://example.com/downloads/indexer-linux-amd64"
    service_name: "indexer"
    description: "Custom Indexer Service"
    user: "indexer"
    group: "indexer"
    working_dir: "/opt/indexer"
    instances:
      - name: "indexer-1"
        port: 8080
        config_file: "/etc/indexer/indexer-1.conf"
      - name: "indexer-2"
        port: 8081
        config_file: "/etc/indexer/indexer-2.conf"
    environment_vars:
      LOG_LEVEL: "info"
      DATA_DIR: "/var/lib/indexer"

# Additional binary example (commented out)
# - name: "another-service"
#   url: "https://example.com/downloads/another-service"
#   service_name: "another"
#   description: "Another Custom Service"
#   user: "another"
#   group: "another"
#   working_dir: "/opt/another"
#   instances:
#     - name: "another-1"
#       port: 9000
#       config_file: "/etc/another/config.yml"