---
# General Configuration
indexer_domain: "localhost"
admin_email: "your-email@domain.com"

# Base Packages to Install
base_packages:
  - curl
  - wget
  - python3
  - apt-transport-https
  - ca-certificates
  - gnupg

# Nginx Configuration
nginx_port: 443

# ClickHouse Configuration
clickhouse_http_port: 8123
clickhouse_tcp_port: 9000
clickhouse_data_dir: "/var/lib/clickhouse"
clickhouse_log_dir: "/var/log/clickhouse-server"
clickhouse_database_name: "ericore"
clickhouse_password: "changeme"

# Prometheus Configuration
prometheus_port: 9090
prometheus_scrape_interval: "15s"

# Grafana Configuration
grafana_port: 3000
grafana_admin_password: "changeme"

# SSL Certificate Configuration
certbot_admin_email: "{{ admin_email }}"
certbot_create_method: "standalone"
certbot_create_extra_args: "--test-cert"
skip_ssl_for_localhost: true
certbot_certs:
  - domains:
      - "{{ indexer_domain }}"