---
# General Configuration
indexer_domain: "ericore.example.com"  # Change this to your actual subdomain
admin_email: "your-email@domain.com"

# Base Packages to Install
base_packages:
  - curl
  - wget
  - python3
  - apt-transport-https
  - ca-certificates
  - gnupg

# Nginx Configuration
nginx_port: 443
# Comment out upstream servers until you have an actual application running
# nginx_upstream_servers:
#   - "127.0.0.1:8080"  # Default upstream server, adjust based on your application

# ClickHouse Configuration
clickhouse_http_port: 8123
clickhouse_tcp_port: 9000
clickhouse_interserver_port: 9009
clickhouse_data_dir: "/var/lib/clickhouse"
clickhouse_log_dir: "/var/log/clickhouse-server"
clickhouse_database_name: "ericore"
clickhouse_password: "changeme"

# Prometheus Configuration
prometheus_port: 9090
prometheus_scrape_interval: "15s"

# Grafana Configuration
grafana_port: 3000
grafana_admin_password: "changeme"

# SSL Certificate Configuration
certbot_admin_email: "{{ admin_email }}"
certbot_create_method: "standalone"
certbot_create_extra_args: "--test-cert"  # Remove this for production certificates
certbot_certs:
  - domains:
      - "{{ indexer_domain }}"