---
- name: Install Redis server
  apt:
    name: redis-server
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Create Redis log directory
  file:
    path: /var/log/redis
    state: directory
    owner: redis
    group: redis
    mode: '0755'

- name: Create Redis configuration file
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: '0640'
    backup: true
  notify: restart redis

- name: Ensure Redis is started and enabled
  systemd:
    name: redis-server
    state: started
    enabled: true
    daemon_reload: true

- name: Wait for Redis to start
  wait_for:
    port: "{{ redis_port }}"
    host: 127.0.0.1
    delay: 2
    timeout: 30

- name: Test Redis connectivity
  command: redis-cli -p {{ redis_port }} ping
  register: redis_ping
  changed_when: false
  failed_when: redis_ping.stdout != "PONG"

- name: Display Redis status
  debug:
    msg: "Redis is running on port {{ redis_port }}"

# Redis Exporter Installation
- name: Create redis exporter user
  user:
    name: "{{ redis_exporter_user }}"
    group: "{{ redis_exporter_group }}"
    system: true
    shell: /bin/false
    home: /nonexistent
    create_home: false
    state: present

- name: Create redis exporter group
  group:
    name: "{{ redis_exporter_group }}"
    system: true
    state: present

- name: Download Redis exporter
  get_url:
    url: "https://github.com/oliver006/redis_exporter/releases/download/v{{ redis_exporter_version }}/redis_exporter-v{{ redis_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/redis_exporter-v{{ redis_exporter_version }}.linux-amd64.tar.gz"
    mode: '0644'

- name: Extract Redis exporter
  unarchive:
    src: "/tmp/redis_exporter-v{{ redis_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: true
    owner: root
    group: root

- name: Install Redis exporter binary
  copy:
    src: "/tmp/redis_exporter-v{{ redis_exporter_version }}.linux-amd64/redis_exporter"
    dest: /usr/local/bin/redis_exporter
    owner: root
    group: root
    mode: '0755'
    remote_src: true

- name: Create Redis exporter systemd service
  copy:
    content: |
      [Unit]
      Description=Redis Exporter
      After=network.target redis-server.service
      Wants=redis-server.service

      [Service]
      Type=simple
      User={{ redis_exporter_user }}
      Group={{ redis_exporter_group }}
      ExecStart=/usr/local/bin/redis_exporter \
        -redis.addr=redis://127.0.0.1:{{ redis_port }} \
        -web.listen-address=:{{ redis_exporter_port }}
      Restart=on-failure
      RestartSec=5
      KillMode=mixed

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/redis_exporter.service
    mode: '0644'
  notify: restart redis_exporter

- name: Start and enable Redis exporter
  systemd:
    name: redis_exporter
    state: started
    enabled: true
    daemon_reload: true

- name: Wait for Redis exporter to start
  wait_for:
    port: "{{ redis_exporter_port }}"
    host: 127.0.0.1
    delay: 2
    timeout: 30

- name: Clean up downloaded files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/redis_exporter-v{{ redis_exporter_version }}.linux-amd64.tar.gz"
    - "/tmp/redis_exporter-v{{ redis_exporter_version }}.linux-amd64"

- name: Display Redis exporter status
  debug:
    msg: "Redis exporter is running on port {{ redis_exporter_port }}"