---
- name: Install nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes
  notify: restart nginx

- name: Create nginx configuration directory
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '0755'
  become: yes

- name: Configure nginx as load balancer
  template:
    src: load_balancer.conf.j2
    dest: "/etc/nginx/conf.d/load_balancer.conf"
    mode: '0644'
  become: yes
  notify: restart nginx

- name: Configure firewall for HTTPS
  ufw:
    rule: allow
    port: '443'
    proto: tcp
  become: yes

- name: Configure firewall for HTTP (for certbot)
  ufw:
    rule: allow
    port: '80'
    proto: tcp
  become: yes

- name: Start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Download nginx-prometheus-exporter
  get_url:
    url: "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.1.0/nginx-prometheus-exporter_1.1.0_linux_amd64.tar.gz"
    dest: "/tmp/nginx-prometheus-exporter.tar.gz"
    mode: '0644'
  become: yes

- name: Extract nginx-prometheus-exporter
  unarchive:
    src: "/tmp/nginx-prometheus-exporter.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Create nginx-exporter systemd service
  copy:
    content: |
      [Unit]
      Description=Nginx Prometheus Exporter
      After=network.target nginx.service

      [Service]
      Type=simple
      User=nobody
      ExecStart=/usr/local/bin/nginx-prometheus-exporter -nginx.scrape-uri=http://localhost/nginx_status
      Restart=always
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/nginx-prometheus-exporter.service
    mode: '0644'
  become: yes

- name: Start and enable nginx-prometheus-exporter
  systemd:
    name: nginx-prometheus-exporter
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes