---
- name: Check if nginx is already installed
  command: which nginx
  register: nginx_installed
  ignore_errors: true
  changed_when: false

- name: Install nginx
  apt:
    name: nginx
    state: present
  become: true
  when: nginx_installed.rc != 0

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true
  notify: restart nginx

- name: Create nginx configuration directory
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '0755'
  become: true

- name: Configure nginx as load balancer with ericore prefix
  template:
    src: load_balancer.conf.j2
    dest: "/etc/nginx/conf.d/ericore-load-balancer.conf"
    mode: '0644'
  become: true
  notify: restart nginx

- name: Configure firewall for HTTPS
  ufw:
    rule: allow
    port: '443'
    proto: tcp
  become: true

- name: Configure firewall for HTTP (for certbot)
  ufw:
    rule: allow
    port: '80'
    proto: tcp
  become: true

- name: Configure firewall for internal HTTPS
  ufw:
    rule: allow
    port: '8443'
    proto: tcp
    src: '10.0.0.0/8'
    comment: 'Internal SSL for backend communication'
  become: true

- name: Ensure web root directory exists
  file:
    path: /var/www/html
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data
  become: true

- name: Copy default index page
  copy:
    src: index.html
    dest: /var/www/html/index.html
    mode: '0644'
    owner: www-data
    group: www-data
  become: true

- name: Test nginx configuration
  command: nginx -t
  become: true
  register: nginx_config_test
  ignore_errors: true

- name: Start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: true
  become: true
  when: nginx_config_test.rc == 0

- name: Display nginx config test errors
  debug:
    msg: "{{ nginx_config_test.stderr }}"
  when: nginx_config_test.rc != 0

- name: Download nginx-prometheus-exporter
  get_url:
    url: "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.1.0/nginx-prometheus-exporter_1.1.0_linux_amd64.tar.gz"
    dest: "/tmp/nginx-prometheus-exporter.tar.gz"
    mode: '0644'
  become: true

- name: Extract nginx-prometheus-exporter
  unarchive:
    src: "/tmp/nginx-prometheus-exporter.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Create nginx-exporter systemd service
  copy:
    content: |
      [Unit]
      Description=Nginx Prometheus Exporter
      After=network.target nginx.service

      [Service]
      Type=simple
      User=nobody
      ExecStart=/usr/local/bin/nginx-prometheus-exporter -nginx.scrape-uri=http://localhost/nginx_status
      Restart=always
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/nginx-prometheus-exporter.service
    mode: '0644'
  become: true

- name: Start and enable nginx-prometheus-exporter
  systemd:
    name: nginx-prometheus-exporter
    state: started
    enabled: true
    daemon_reload: yes
  become: true