---
- name: Add Grafana GPG key
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present
  become: yes

- name: Add Grafana repository
  apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: present
    filename: grafana
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present
  become: yes

- name: Configure Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: '0640'
  become: yes
  notify: restart grafana

- name: Create Grafana provisioning directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: grafana
    mode: '0755'
  loop:
    - /etc/grafana/provisioning/datasources
    - /etc/grafana/provisioning/dashboards
  become: yes

- name: Provision Prometheus datasource
  template:
    src: prometheus-datasource.yml.j2
    dest: /etc/grafana/provisioning/datasources/prometheus.yml
    owner: root
    group: grafana
    mode: '0640'
  become: yes
  notify: restart grafana

- name: Create dashboard provider config
  copy:
    content: |
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          allowUiUpdates: true
          options:
            path: /etc/grafana/provisioning/dashboards
    dest: /etc/grafana/provisioning/dashboards/dashboard-provider.yml
    owner: root
    group: grafana
    mode: '0640'
  become: yes

- name: Create ClickHouse dashboard
  template:
    src: clickhouse-dashboard.json.j2
    dest: /etc/grafana/provisioning/dashboards/clickhouse.json
    owner: root
    group: grafana
    mode: '0640'
  become: yes
  notify: restart grafana

- name: Create Nginx dashboard
  template:
    src: nginx-dashboard.json.j2
    dest: /etc/grafana/provisioning/dashboards/nginx.json
    owner: root
    group: grafana
    mode: '0640'
  become: yes
  notify: restart grafana

- name: Create Redis dashboard
  template:
    src: redis-dashboard.json.j2
    dest: /etc/grafana/provisioning/dashboards/redis.json
    owner: root
    group: grafana
    mode: '0640'
  become: yes
  notify: restart grafana

- name: Configure firewall for Grafana
  ufw:
    rule: allow
    port: "{{ grafana_port }}"
    proto: tcp
  become: yes

- name: Start and enable Grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes
  become: yes