---
- name: Clean up ericore-specific configurations
  hosts: servers
  become: true
  gather_facts: false
  tasks:
    - name: Stop nginx if running
      systemd:
        name: nginx
        state: stopped
      ignore_errors: true

    - name: Remove ericore-specific nginx configurations
      shell: |
        rm -f /etc/nginx/sites-enabled/ericore-*
        rm -f /etc/nginx/sites-available/ericore-*
        rm -f /etc/nginx/conf.d/ericore-*
      ignore_errors: true

    - name: Remove existing SSL certificates for the domain
      shell: |
        rm -rf /etc/letsencrypt/live/{{ indexer_domain }}
        rm -rf /etc/letsencrypt/archive/{{ indexer_domain }}
        rm -f /etc/letsencrypt/renewal/{{ indexer_domain }}.conf
      ignore_errors: true
      when: indexer_domain is defined

    - name: Ensure nginx is installed
      apt:
        name: 
          - nginx
          - nginx-common
        state: present
        update_cache: true
        cache_valid_time: 3600

- name: Display all variables at start
  hosts: servers
  gather_facts: false
  tasks:
    - name: Log all important variables
      debug:
        msg:
          - "=== DEPLOYMENT CONFIGURATION ==="
          - "Domain: {{ indexer_domain }}"
          - "Admin Email: {{ admin_email }}"
          - "ClickHouse Password: {{ clickhouse_password }}"
          - "Grafana Admin Password: {{ grafana_admin_password }}"
          - "Certbot Method: {{ certbot_create_method }}"
          - "Certbot Extra Args: {{ certbot_create_extra_args }}"
          - "Nginx Port: {{ nginx_port }}"
          - "================================="

- name: Configure all servers with common setup
  hosts: servers
  become: true
  roles:
    - common

- name: Generate local SSL certificates for internal communication
  hosts: servers
  become: true
  roles:
    - local-certs

- name: Configure SSL certificates
  hosts: nginx_servers
  become: true
  roles:
    - certs

- name: Configure nginx load balancers
  hosts: nginx_servers
  become: true
  roles:
    - nginx

- name: Configure ClickHouse servers
  hosts: clickhouse_servers
  become: true
  roles:
    - clickhouse

- name: Configure Prometheus servers
  hosts: prometheus_servers
  become: true
  roles:
    - prometheus

- name: Configure Grafana servers
  hosts: grafana_servers
  become: true
  roles:
    - grafana