---
- name: Clean up existing configurations
  hosts: servers
  become: true
  gather_facts: false
  tasks:
    - name: Stop nginx if running
      systemd:
        name: nginx
        state: stopped
      ignore_errors: true

    - name: Remove nginx package
      apt:
        name: nginx
        state: absent
        purge: true
      ignore_errors: true

    - name: Remove nginx configuration directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx
        - /var/log/nginx
        - /var/www/html
      ignore_errors: true

    - name: Remove existing SSL certificates
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/letsencrypt
        - /etc/ssl/certs/localhost.crt
        - /etc/ssl/private/localhost.key
      ignore_errors: true

    - name: Remove nginx systemd files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/systemd/system/nginx.service
        - /lib/systemd/system/nginx.service
      ignore_errors: true

    - name: Reload systemd daemon
      systemd:
        daemon_reload: true

- name: Display all variables at start
  hosts: servers
  gather_facts: false
  tasks:
    - name: Log all important variables
      debug:
        msg:
          - "=== DEPLOYMENT CONFIGURATION ==="
          - "Domain: {{ indexer_domain }}"
          - "Admin Email: {{ admin_email }}"
          - "ClickHouse Password: {{ clickhouse_password }}"
          - "Grafana Admin Password: {{ grafana_admin_password }}"
          - "Certbot Method: {{ certbot_create_method }}"
          - "Certbot Extra Args: {{ certbot_create_extra_args }}"
          - "Skip SSL for localhost: {{ skip_ssl_for_localhost }}"
          - "Nginx Port: {{ nginx_port }}"
          - "================================="

- name: Configure all servers with common setup
  hosts: servers
  become: true
  roles:
    - common

- name: Configure SSL certificates
  hosts: nginx_servers
  become: true
  roles:
    - certs

- name: Configure nginx load balancers
  hosts: nginx_servers
  become: true
  roles:
    - nginx

- name: Configure ClickHouse servers
  hosts: clickhouse_servers
  become: true
  roles:
    - clickhouse

- name: Configure Prometheus servers
  hosts: prometheus_servers
  become: true
  roles:
    - prometheus

- name: Configure Grafana servers
  hosts: grafana_servers
  become: true
  roles:
    - grafana