---
- name: Clean up and reinstall nginx with fresh configuration
  hosts: servers
  become: true
  gather_facts: false
  tasks:
    - name: Stop nginx if running
      systemd:
        name: nginx
        state: stopped
      ignore_errors: true

    - name: Remove nginx package completely
      apt:
        name: nginx
        state: absent
        purge: true
        autoremove: true
      ignore_errors: true

    - name: Remove all nginx configuration and data
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx
        - /var/log/nginx
        - /var/cache/nginx
        - /usr/share/nginx
        - /var/lib/nginx
      ignore_errors: true

    - name: Update package cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install nginx fresh
      apt:
        name: 
          - nginx
          - nginx-common
        state: present
        install_recommends: true

    - name: Ensure nginx is stopped after fresh install
      systemd:
        name: nginx
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Backup original nginx configuration
      copy:
        src: /etc/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf.original
        mode: '0644'
        remote_src: true
      ignore_errors: true

- name: Display all variables at start
  hosts: servers
  gather_facts: false
  tasks:
    - name: Log all important variables
      debug:
        msg:
          - "=== DEPLOYMENT CONFIGURATION ==="
          - "Domain: {{ indexer_domain }}"
          - "Admin Email: {{ admin_email }}"
          - "ClickHouse Password: {{ clickhouse_password }}"
          - "Grafana Admin Password: {{ grafana_admin_password }}"
          - "Certbot Method: {{ certbot_create_method }}"
          - "Certbot Extra Args: {{ certbot_create_extra_args }}"
          - "Skip SSL for localhost: {{ skip_ssl_for_localhost }}"
          - "Nginx Port: {{ nginx_port }}"
          - "================================="

- name: Configure all servers with common setup
  hosts: servers
  become: true
  roles:
    - common

- name: Configure SSL certificates
  hosts: nginx_servers
  become: true
  roles:
    - certs

- name: Configure nginx load balancers
  hosts: nginx_servers
  become: true
  roles:
    - nginx

- name: Configure ClickHouse servers
  hosts: clickhouse_servers
  become: true
  roles:
    - clickhouse

- name: Configure Prometheus servers
  hosts: prometheus_servers
  become: true
  roles:
    - prometheus

- name: Configure Grafana servers
  hosts: grafana_servers
  become: true
  roles:
    - grafana