---
- name: Clean up ericore-specific configurations
  hosts: servers
  become: true
  gather_facts: false
  tasks:
    - name: Stop nginx if running
      systemd:
        name: nginx
        state: stopped
      ignore_errors: true

    - name: Remove ALL nginx site configurations (clean slate)
      shell: |
        rm -f /etc/nginx/sites-enabled/*
        rm -f /etc/nginx/sites-available/*
        rm -f /etc/nginx/conf.d/*
      ignore_errors: true
      
    - name: Remove old SSL certificates from previous domains
      shell: |
        rm -rf /etc/letsencrypt/live/*
        rm -rf /etc/letsencrypt/archive/*
        rm -f /etc/letsencrypt/renewal/*.conf
      ignore_errors: true

    - name: Stop ClickHouse service
      systemd:
        name: clickhouse-server
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Remove ClickHouse packages
      apt:
        name:
          - clickhouse-server
          - clickhouse-client
        state: absent
        purge: true
        autoremove: true
      ignore_errors: true

    - name: Remove ClickHouse directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/clickhouse-server
        - /var/lib/clickhouse
        - /var/log/clickhouse-server
      ignore_errors: true

    - name: Force remove any remaining ClickHouse configs and reload systemd
      shell: |
        systemctl daemon-reload
        find /etc -name "*clickhouse*" -type f -delete 2>/dev/null || true
        find /var -name "*clickhouse*" -type d -exec rm -rf {} + 2>/dev/null || true
        systemctl reset-failed clickhouse-server.service 2>/dev/null || true
        echo "ClickHouse completely purged"
      ignore_errors: true


    - name: Ensure nginx is installed
      apt:
        name: 
          - nginx
          - nginx-common
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: Stop nginx to ensure clean restart
      systemd:
        name: nginx
        state: stopped
      ignore_errors: true

- name: Display all variables at start
  hosts: servers
  gather_facts: false
  tasks:
    - name: Log all important variables
      debug:
        msg:
          - "=== DEPLOYMENT CONFIGURATION ==="
          - "Domain: {{ indexer_domain }}"
          - "Admin Email: {{ admin_email }}"
          - "ClickHouse Password: {{ clickhouse_password }}"
          - "Grafana Admin Password: {{ grafana_admin_password }}"
          - "Certbot Method: {{ certbot_create_method }}"
          - "Certbot Extra Args: {{ certbot_create_extra_args }}"
          - "Nginx Port: {{ nginx_port }}"
          - "================================="

- name: Configure all servers with common setup
  hosts: servers
  become: true
  roles:
    - common

- name: Generate local SSL certificates for internal communication
  hosts: servers
  become: true
  roles:
    - local-certs

- name: Configure SSL certificates
  hosts: nginx_servers
  become: true
  roles:
    - certs

- name: Configure nginx load balancers
  hosts: nginx_servers
  become: true
  roles:
    - nginx

- name: Configure ClickHouse servers
  hosts: clickhouse_servers
  become: true
  roles:
    - clickhouse

- name: Configure Prometheus servers
  hosts: prometheus_servers
  become: true
  roles:
    - prometheus

- name: Configure Grafana servers
  hosts: grafana_servers
  become: true
  roles:
    - grafana