---
- name: restart redis
  systemd:
    name: redis-server
    state: restarted
    daemon_reload: true

- name: reload redis
  systemd:
    name: redis-server
    state: reloaded

- name: restart redis_exporter
  systemd:
    name: redis_exporter
    state: restarted
    daemon_reload: true