---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Upgrade all packages
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
  become: true

- name: Install base dependencies
  apt:
    name: "{{ base_packages }}"
    state: present
  become: true

- name: Install ufw firewall
  apt:
    name: ufw
    state: present
  become: true

- name: Configure UFW defaults
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  become: true
  loop:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }

- name: Allow SSH access
  ufw:
    rule: allow
    port: '22'
    proto: tcp
  become: true

- name: Allow HTTP access (port 80) for Let's Encrypt
  ufw:
    rule: allow
    port: '80'
    proto: tcp
  become: true

- name: Allow HTTPS access (port 443)
  ufw:
    rule: allow
    port: '443'
    proto: tcp
  become: true

- name: Enable UFW
  ufw:
    state: enabled
  become: true

- name: Gather network facts
  setup:
    gather_subset:
      - network

- name: Get public IP address
  uri:
    url: https://ipinfo.io/ip
    return_content: yes
  register: public_ip
  ignore_errors: true

- name: Set fact for public IP
  set_fact:
    server_public_ip: "{{ public_ip.content | default('N/A') | trim }}"

- name: Set fact for private IP
  set_fact:
    server_private_ip: "{{ ansible_default_ipv4.address | default('N/A') }}"

- name: Display server information
  debug:
    msg:
      - "Server Hostname: {{ ansible_hostname }}"
      - "Public IP: {{ server_public_ip }}"
      - "Private IP: {{ server_private_ip }}"
      - "All IPv4 addresses: {{ ansible_all_ipv4_addresses | join(', ') }}"